version: 2

models:
  - name: ohlcv_1h
    columns:
      - name: symbol
        tests:
          - not_null
      - name: hour_start
        tests:
          - not_null

  - name: anomaly_summary
    columns:
      - name: symbol
        tests:
          - not_null
      - name: day
        tests:
          - not_null